name: PDPTW
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11

  - numpy
  - pandas

  - gymnasium

  - matplotlib
  - seaborn

  - pyyaml
  - pyparsing

  - pybind11
  - setuptools
  - tensorboard

  - pytorch::pytorch          
  - conda-forge::scipy

  - pip
  - pip:
    - ortools  
